### ISSUE TITLE
Problem with foamextend 4.0 run damBreak

### ISSUE THREAD

**Issue by simomartini** [isoAdvector/isoAdvector#12]
I installed isoAdvector following the Github instructions with some slight fix to make it work on foam-extend-4.0. The compilation was successful. I then tried to take the damBreak tutorial case

Unfortunately the tutorial does not work. It gives me an error that I make the run:

> --> FOAM FATAL ERROR:

>flux requested but pcorr not specified in the fluxRequired sub-dictionary of fvSchemes.
>  From function fvMatrix<Type>::flux()
>   in file /home/smartini/foam/foam-extend-4.0/src/finiteVolume/lnInclude/fvMatrix.C at line 1046.

>FOAM aborting

>Aborted (core dumped)

In fvSolotion, however, I correctly specified pcorr in the fluxRequired variable so I do not know what's wrong with it.
I included the case. Does anyone have any suggestions?

Kind Regards 
[damBreakfe40.zip](https://github.com/isoAdvector/isoAdvector/files/1736748/damBreakfe40.zip)

**Comment by isoAdvector** [comment]
Hi Simon

Sorry for the late reply. 

As stated in the README, the foam-extend version of the code is currently available and was developed for foam-extend-32, but does not contain the latest code developments. So it will require some work to get it to work with the latest foam-extend version. As all OpenFOAM developers, I have to choose between spending all my time keeping to code working with all OpenFOAM/FOAM versions and actually developing and improving the code. I have chosen the latter.

Best,
Johan

**Comment by simomartini** [comment]
Hi Johan,
I thank you for the answer. Do you think you will also upgrade for foam extend? I installed isoAdvector on foam-extend-3.2 and as you suggested it works fine. I would like to try to correct the code also for foam extend 4.0. Would you have a suggestion on this? On which .C or .H file could there be an error?

Kind regards 
Simone

**Comment by isoAdvector** [comment]
I might update it at some point, but cannot say when (or if). Have to prioritize. Sorry. Ideally, someone with the right skills would do it and contribute it to the project.
