### ISSUE TITLE
Porting to foam-extend-3.2 quite complicated

### ISSUE THREAD

**Issue by ma-tri-x** [isoAdvector/isoAdvector#15]
Dear isoAdvector programmers and Roenby,

I tried to use isoAdvector with our foam-extend-3.2 solver. We got a stable working version for both incompressible and compressible flows for single thread calculations when using the "foam-extend" directory from the isoAdvector repo. However, the results are doubtful and in multiple thread calcs it runs into strange behaviours and parallelisation issues.
As discussed in #11 I then tried to port the OpenFOAM directory from the isoAdvector repo to a working version for foam-extend-3.2 via altering the script "bin/generateCodeForOldVersion.sh". Sadly, it seems really not to be that easy. The bash script does not cover all differences. For instance there is no OBJstream.H in foam-extend-3.2 and there are several objects being used in isoAdvector using these streams. Also OpenFOAM uses different namespaces. I completed the work to make the isoAdvector/src directory compile for foam-extend-3.2 but applications, utilities and solvers still run into compile errors. Do I necessarily need them to isoAdvect my interface in my solver?

Best regards,
ma-tri-x

**Comment by isoAdvector** [comment]
Hi ma-tri-x

If you have the isoAdvectorsrc compiling and working correctly with foam-extend you should be almost there.

The interFoam code in foam-extend is really very similar to the one in OpenFOAM, and the changes you need to do to generate interFlow from that are really quite minor. Try to compare e.g the interFoam-2.2.0 solver files and interFlow-2.2.0 solver files to spot the difference and then make similar changes to the foam-extend version of the interFoam files. It is basically a matter of removing MULES in alphaEqn.H and replacing it by isoAdvector.

Good luck.

Best,
Johan

**Comment by ma-tri-x** [comment]
Hi Johann,

I compiled the modified isoAdvector/src, created the interFlow solver, and put a bubble into a homogeneous flow on an axisymmetric mesh that I decomposed with "simple" into four parts on the y-axis. One can clearly observe the gas that remains in the cells close to a processor boundary, where the bubble has crossed. So the issue seems to remain. Precisely, it's the cells of the processor that the bubble goes to (not of the former processor where the bubble comes from).

To be sure I really used the new libisoAdvector, I deleted it manually in $FOAM_USER_LIBBIN and recompiled it. So did I with interFlow in $FOAM_USER_APPBIN.

![processor_problems](https://user-images.githubusercontent.com/12648792/40177984-7814fe46-59e0-11e8-8416-a7a42ddd2490.png)

Since there are major differences in the IOstream code, I suppose there's an issue with the interprocessor-stream. I had to modify some parts of the ported code inside "::syncProcPatches". The function now looks like the old one:
```
void Foam::isoAdvection::syncProcPatches
(
    surfaceScalarField& dVf,
    const surfaceScalarField& phi
)
{
    const polyBoundaryMesh& patches = mesh_.boundaryMesh();

    if (Pstream::parRun())
    {
        //PstreamBuffers pBufs(Pstream::nonBlocking);

        // Send
        forAll(procPatchLabels_, i)
        {
            const label patchi = procPatchLabels_[i];

            const processorPolyPatch& procPatch =
                refCast<const processorPolyPatch>(patches[patchi]);

            OPstream toNbr(Pstream::blocking, procPatch.neighbProcNo());
            const scalarField& pFlux = dVf.boundaryField()[patchi];

            const List<label>& surfCellFacesOnProcPatch =
                surfaceCellFacesOnProcPatches_[patchi];

            const UIndirectList<scalar> dVfPatch
            (
                pFlux,
                surfCellFacesOnProcPatch
            );

            toNbr << surfCellFacesOnProcPatch << dVfPatch;
        }

        //pBufs.finishedSends();


        // Receive and combine
        forAll(procPatchLabels_, patchLabeli)
        {
            const label patchi = procPatchLabels_[patchLabeli];

            const processorPolyPatch& procPatch =
                refCast<const processorPolyPatch>(patches[patchi]);

            IPstream fromNeighb(Pstream::blocking, procPatch.neighbProcNo());
            List<label> faceIDs;
            List<scalar> nbrdVfs;

            fromNeighb >> faceIDs >> nbrdVfs;

            if (debug)
            {
                Pout<< "Received at time = " << mesh_.time().value()
                    << ": surfCellFacesOnProcPatch = " << faceIDs << nl
                    << "Received at time = " << mesh_.time().value()
                    << ": dVfPatch = " << nbrdVfs << endl;
            }

            // Combine fluxes
            scalarField& localFlux = dVf.boundaryField()[patchi];

            forAll(faceIDs, i)
            {
                const label facei = faceIDs[i];
                localFlux[facei] = - nbrdVfs[i];
                if (debug && mag(localFlux[facei] + nbrdVfs[i]) > 10*SMALL)
                {
                    Pout<< "localFlux[facei] = " << localFlux[facei]
                        << " and nbrdVfs[i] = " << nbrdVfs[i]
                        << " for facei = " << facei << endl;
                }
            }
        } 

        if (debug)
        {
            // Write out results for checking
            forAll(procPatchLabels_, patchLabeli)
            {
                const label patchi = procPatchLabels_[patchLabeli];
                const scalarField& localFlux = dVf.boundaryField()[patchi];
                Pout<< "time = " << mesh_.time().value() << ": localFlux = "
                    << localFlux << endl;
            }
        }

        // Reinitialising list used for minimal parallel communication
        forAll(surfaceCellFacesOnProcPatches_, patchi)
        {
            surfaceCellFacesOnProcPatches_[patchi].clear();
        }
    }
}
```

**Comment by ma-tri-x** [comment]
I fear this is above my OpenFoam skills. Do you have any clue why I observe processor patch flux errors even with the recent isoAdvector code?

**Comment by isoAdvector** [comment]
Hi ma-tri-x

Sorry but currently I have to limit my work to the OpenFOAM version of isoAdvector. 

Sounds like a good strategy to start by copying the syncProcPatches function from the foam-extend version of isoAdvection into your code.

Keep digging. You'll learn a lot. Make sure to use as simple test cases as possible. Look for places in the foam-extend src library where they do similar stuff and try to copy their approach.

Good luck,
Johan

**Comment by ma-tri-x** [comment]
Sorry, I didn't mean you to spend hours on it!! I would be grateful if you have any suggestions coming to your mind after reading the message. Maybe you can already see from the code above, that there are some lines that are not correct like that (order is different than in OF version) and give some hints. Or, if not, suggest things I could do. I'm not refusing to learn! But hints from the pros accelerate the way to success quite much and in the end you'll have an up-to-date foam-extend branch, too, done by someone else. Sorry if I transported lazyness. I'm working with foam-extend since 5 years, so I should have some essential skills.
