### ISSUE TITLE
Unphysical alpha separation at sharp, high curvature boundary layers

### ISSUE THREAD

**Issue by MartinKlevs** [isoAdvector/isoAdvector#17]
I am using this library on a case that involves argon bubbles rising in liquid gallium. I have an issue where the alpha field "leaks" near the edges of the bubbles, and subsequently forms smaller bubbles roughly the size of a mesh cell. This was way more intense with MULES, however using isoAdvector still doesn't solve it.

There are sharp gradients at the edges of the bubbles, however this separation shouldn't happen in my setup.

Here are some isoFaces that showcase this behaviour.

![iso_1_1](https://user-images.githubusercontent.com/31007480/113618478-6a564e80-9660-11eb-8455-0a571d56c859.png)

![iso_1_2](https://user-images.githubusercontent.com/31007480/113618484-6c201200-9660-11eb-9fbc-91159f976481.png)

![iso_2_1](https://user-images.githubusercontent.com/31007480/113618494-6e826c00-9660-11eb-8405-c46b397dc9ba.png)

![iso_2_2](https://user-images.githubusercontent.com/31007480/113618505-717d5c80-9660-11eb-9da8-2b9578e0d2b6.png)

![iso_3_1](https://user-images.githubusercontent.com/31007480/113618500-704c2f80-9660-11eb-8579-1b4e31ee2054.png)

The isoFaces look weird to me. It looks like a second surface layer is forming at the "leakage" zone. 

I have tweaked all of the main solver parameters for alpha and p_rgh fields, and it doesn't seem to help. Lowering the Courant number also doesn't help. My _p_rghfinal_ is 1e-10 and _soFaceTol_ is 1e-6 and _surfCellTol_ is 1e-6. The artefact sizes seem to correlate with cell sizes. I have tested this in v6 and v2012.

Any help would be greatly appreciated.

**Comment by roenby** [comment]
Could you try uploading a cleaned case (2012 version) including an Allrun script?
Have you tried with the interIsoFoam solver of v2012?
That is the most up-to-date and bug-fixed isoAdvector version.

**Comment by MartinKlevs** [comment]
Here is the case:
[https://drive.google.com/file/d/1_09IYoYAvuWly7Q0ogmc_TPzEHNANufN/view?usp=sharing](https://drive.google.com/file/d/1_09IYoYAvuWly7Q0ogmc_TPzEHNANufN/view?usp=sharing)

Note: the effect is fully observable on the first few bubbles. Simulating until t=0.25-0.5s is sufficient.

**Comment by roenby** [comment]
Hi Martin

Please see my comment over at [https://develop.openfoam.com/Development/openfoam/-/issues/2052]()
