### ISSUE TITLE
Missing update to "rho" and "rhoPhi" for HRIC/CICSAM schemes

### ISSUE THREAD

**Issue by furstj** [isoAdvector/isoAdvector#4]
When choosing interfaceMethod "fvSchemes" the interFlow solver solves just the equation for alpha1 but it doesn't update "rho" and "rhoPhi" fields. Therefore it gives wrong results e.g. for dam break problem. Changing the "fvSchemes" branch in advectInterface.H to the following remedies the solver.

Best regards and congratulations for the isoAdvector method,
 Jiri Furst
======================================
....
else if (interfaceMethod == "fvSchemes")
{
    fvScalarMatrix alpha1Eqn
        (
            fvm::ddt(alpha1)
            + fvm::div(phi, alpha1)
            -
            fvOptions(alpha1)
        );
    
    alpha1Eqn.solve();
    alpha2 = 1.0 - alpha1;
    mixture.correct();
    
    rho = alpha1*rho1 + alpha2*rho2;
    rhoPhi = alpha1Eqn.flux() * (rho1 - rho2) + phi*rho2;
}
=======================================

**Comment by isoAdvector** [comment]
Thanks a lot, Jiri. It means a lot to me to get this kind og bug fixes so the code can continuously be improved. I will include the correction in the next "release".

**Comment by isoAdvector** [comment]
Fixed in commit 74c5f5dbdd54bb4bcc4bb8c671d2387d2edefa87 to branch miscCodeCleaning
