### ISSUE TITLE
Imposed time-dependant velocity field does not work when the alpha equation is advected with MULES or fvSchemes 

### ISSUE THREAD

**Issue by GonzaloSaez** [isoAdvector/isoAdvector#6]
Dear Mr. Roenby,

I am trying to compare the different spatial and temporal convergence orders using isoAdvector and MULES. When working with the vortexShearedDisc validation testcase, I noticed that the simulations using the MULES method had a constant velocity field. I soon realized that this was because the velocity field was not updated when using the MULES or fvSchemes methods.

This issue is easy to solve. Just, create a file _updateU.H_ with the following code

```
if (prescribedU) 
{
    //Setting velocity field and face fluxes for next time step
    const scalar t(runTime.time().value());
    const scalar dt(runTime.deltaT().value());
    if (reverseTime > 0.0 && t >= reverseTime)
    {
        Info<< "Reversing flow" << endl;
        phi *= -1.0;
        U *= -1.0;
        reverseTime = -1.0;
    }
    if (period > 0.0)
    {
        const scalar uFactor
        (
            .5*(Foam::cos(2.0*M_PI*t/period) 
                + Foam::cos(2.0*M_PI*(t + dt)/period))
        );
        phi = uFactor*phi0;
        U = uFactor*U0;
    }
}
```

This file should be included in the first line of the file _advectInterface.H_ 

Moreover these lines of code should also be erased from the file _isoAdvectInterface.H_

I am sorry for not being able of creating a proper formatted issue but my current workspace doesn't allow me to use git. Next week I should be able to create a pull request with the bug fix

**Comment by isoAdvector** [comment]
Good point, thanks a lot. This has now been corrected in the develop branch commit 780a8ea.
